"Module: twinkle":
  - src/twinkle.js
  - src/twinkle.css
  - src/twinkle-pagestyles.css
"Module: morebits":
  - src/morebits.js
  - src/morebits.css
"Module: arv":
  - src/modules/twinklearv.js
"Module: batch":
  - src/modules/twinklebatchdelete.js
  - src/modules/twinklebatchundelete.js
  - src/modules/twinklebatchprotect.js
  - src/modules/twinkledeprod.js
"Module: block":
  - src/modules/twinkleblock.js
"Module: config":
  - src/modules/twinkleconfig.js
"Module: diff":
  - src/modules/twinklediff.js
"Module: prod":
  - src/modules/twinkleprod.js
"Module: protect":
  - src/modules/twinkleprotect.js
"Module: rollback":
  - src/modules/twinklerollback.js
"Module: speedy":
  - src/modules/twinklespeedy.js
  - src/modules/twinkleimage.js
"Module: tag":
  - src/modules/twinkletag.js
"Module: talkback":
  - src/modules/twinkletalkback.js
"Module: unlink":
  - src/modules/twinkleunlink.js
"Module: warn":
  - src/modules/twinklewarn.js
"Module: welcome":
  - src/modules/twinklewelcome.js
"Module: xfd":
  - src/modules/twinklexfd.js
Tests:
  - tests/*
Docs:
  - "*.md"
Gadget:
  - gadget.txt
dependencies:
  - package.json
  - package-lock.json
